**Setup**

Start by running the cell below to import `pandas` and import the exercise datasets.

In [1]:
import pandas as pd
csat = pd.read_csv('csat.csv')
csat.head()

review_id current_plan_start  days_subscribed date_reviewed pay_freq  \
0      38538         2022-08-29              229    2023-04-15   Yearly   
1      78458         2022-04-11              279    2023-01-15      NaN   
2      16139         2022-01-19              422    2023-03-17      NaN   
3      88142         2022-02-26              454    2023-05-26   Yearly   
4      21901         2022-05-27               84    2022-08-19      NaN   

      level  rating first_level  
0   Premium       2        Free  
1      Free       5    Standard  
2      Free       3     Premium  
3  Standard       3    Standard  
4      Free       4     Premium

**1. Collect Numeric Data**

Call `.describe` on the `days_subscribed` column.

In [2]:
csat['days_subscribed'].describe()

count    30000.000000
mean       248.127300
std        236.142417
min          0.000000
25%         36.000000
50%        171.000000
75%        425.000000
max        790.000000
Name: days_subscribed, dtype: float64

**2. Use `.describe` to classify rows**

Write a function `quarter` that categorizes rows based on the percentiles from `.describe`. Specifically, `quarter` should output

- `Q1` for any rows with `days_subscribed` less than or equal to `36`
- `Q2` for any rows with `days_subscribed` greater than `36` and less than or equal to `171`
- `Q3` for any rows with `days_subscribed` greater than `171` and less than or equal to `425`
- `Q4` for any rows with `days_subscribed` greater than `425` and less than or equal to `790`

In [5]:
def quarter(column):
    if column <= 36:
        return 'Q1'
    elif column > 36 and column <= 171:
        return 'Q2'
    elif column > 171 and column >= 425:
        return 'Q3'
    elif column > 425 and column <=790:
        return 'Q4'
    else:
        return 'Outlier'

**3. Apply `quarter` to `csat`**

Apply `quarter` to create a new column `'quarter'` in the `csat` DataFrame that contains the output of `quarter` on each row.

In [8]:
csat['quarter'] = csat['days_subscribed'].apply(quarter)
csat['quarter']

0        Outlier
1        Outlier
2        Outlier
3             Q3
4             Q2
          ...   
29995         Q3
29996         Q2
29997         Q1
29998         Q1
29999         Q1
Name: quarter, Length: 30000, dtype: object

**4. Summarize Negative Ratings**

Write a function that returns the percent of negative (1 or 2 star) ratings.

In [9]:
def negative_percent(column):
    negative_count = column.value_counts().loc[1] + column.value_counts().loc[2]
    negative_percent = negative_count / len(column)
    return negative_percent

**5. Calculate Negative Ratings by `quarter`**

Use `groupby` and `apply` to compute the percent of negative ratings for each `quarter` grouping.

In [12]:
negative_percent_by_quarter= csat.groupby('quarter')['rating'].apply(negative_percent)
print(negative_percent_by_quarter)

quarter
Outlier    0.221227
Q1         0.214743
Q2         0.228168
Q3         0.230913
Name: rating, dtype: float64
